1: Exploratory Data Analysis and Preprocessing

Sentiment analysis on 1.6 million tweets. Context
This is the sentiment140 dataset. It contains 1,600,000 tweets extracted using the
twitter api . The tweets have been annotated (0 = negative, 4 = positive) and they
can be used to detect sentiment


In [ ]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
from tqdm.notebook import tqdm
import numpy as np 
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Data/tweets.csv",encoding='latin-1')

In [ ]:
df

2401  Borderlands  Positive  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74676  9200       Nvidia  Positive   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
0      I am coming to the borders and I will kill you...     
1      im getting on borderlands and i will kill you ...     
2      im coming on borderlands and i will murder you...     
3      im getting on borderlands 2 and i will murder ...     
4      im getting into borderlands and i can murder y...     
...                                                  ...     
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partition is ...     
74678  Just realized the windows partition of my Mac ...     
74679  Just realized between the windows partition of...     
74680  Just like the windows partition of my Mac is l...     

[74681 rows x 4 columns]

In [ ]:
df.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

  im getting on borderlands and i will murder you all ,  
0  I am coming to the borders and I will kill you...     
1  im getting on borderlands and i will kill you ...     
2  im coming on borderlands and i will murder you...     
3  im getting on borderlands 2 and i will murder ...     
4  im getting into borderlands and i can murder y...

In [ ]:
df.tail()

2401 Borderlands  Positive  \
74676  9200      Nvidia  Positive   
74677  9200      Nvidia  Positive   
74678  9200      Nvidia  Positive   
74679  9200      Nvidia  Positive   
74680  9200      Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partition is ...     
74678  Just realized the windows partition of my Mac ...     
74679  Just realized between the windows partition of...     
74680  Just like the windows partition of my Mac is l...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype 
---  ------                                                 --------------  ----- 
 0   2401                                                   74681 non-null  int64 
 1   Borderlands                                            74681 non-null  object
 2   Positive                                               74681 non-null  object
 3   im getting on borderlands and i will murder you all ,  73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB


In [ ]:
df.describe()

2401
count  74681.000000
mean    6432.640149
std     3740.423819
min        1.000000
25%     3195.000000
50%     6422.000000
75%     9601.000000
max    13200.000000

In [ ]:
df = df.drop(["2401","Borderlands"],axis=1)

In [ ]:
df

Positive im getting on borderlands and i will murder you all ,
0      Positive  I am coming to the borders and I will kill you...   
1      Positive  im getting on borderlands and i will kill you ...   
2      Positive  im coming on borderlands and i will murder you...   
3      Positive  im getting on borderlands 2 and i will murder ...   
4      Positive  im getting into borderlands and i can murder y...   
...         ...                                                ...   
74676  Positive  Just realized that the Windows partition of my...   
74677  Positive  Just realized that my Mac window partition is ...   
74678  Positive  Just realized the windows partition of my Mac ...   
74679  Positive  Just realized between the windows partition of...   
74680  Positive  Just like the windows partition of my Mac is l...   

[74681 rows x 2 columns]

In [ ]:
# rename a single column
df = df.rename(columns={'Positive':'Rating',"im getting on borderlands and i will murder you all ,":"Reviews"})

In [ ]:
df

Rating                                            Reviews
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[74681 rows x 2 columns]

In [ ]:
df.shape

(74681, 2)

In [ ]:
df = df.dropna()

In [ ]:
df

Rating                                            Reviews
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[73995 rows x 2 columns]

In [ ]:
df.shape

(73995, 2)

In [ ]:
set(df.Rating)

{'Irrelevant', 'Negative', 'Neutral', 'Positive'}

In [ ]:
df.Rating.value_counts()

Negative      22358
Positive      20654
Neutral       18108
Irrelevant    12875
Name: Rating, dtype: int64

In [ ]:
df = df[df.Rating.isin(['Irrelevant', 'Negative', 'Neutral', 'Positive'])]

In [ ]:
df.Rating.value_counts()

Negative      22358
Positive      20654
Neutral       18108
Irrelevant    12875
Name: Rating, dtype: int64

In [ ]:
possible_labels = df.Rating.unique()

In [ ]:
possible_labels

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [ ]:
label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index

In [ ]:
label_dict

{'Positive': 0, 'Neutral': 1, 'Negative': 2, 'Irrelevant': 3}

In [ ]:
df.Rating.unique()

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [ ]:
df.Rating = df['Rating'].map(label_dict)

In [ ]:
df.Rating.unique()

array([0, 1, 2, 3])

In [ ]:
df.head(10)

Rating                                            Reviews
0       0  I am coming to the borders and I will kill you...
1       0  im getting on borderlands and i will kill you ...
2       0  im coming on borderlands and i will murder you...
3       0  im getting on borderlands 2 and i will murder ...
4       0  im getting into borderlands and i can murder y...
5       0  So I spent a few hours making something for fu...
6       0  So I spent a couple of hours doing something f...
7       0  So I spent a few hours doing something for fun...
8       0  So I spent a few hours making something for fu...
9       0  2010 So I spent a few hours making something f...

2: Training/Validation Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(df.index.values, 
                                                  df.Rating.values, 
                                                  test_size=0.15, 
                                                  random_state=42,
                                                  stratify=df.Rating.values)

In [ ]:
df.head()

Rating                                            Reviews
0       0  I am coming to the borders and I will kill you...
1       0  im getting on borderlands and i will kill you ...
2       0  im coming on borderlands and i will murder you...
3       0  im getting on borderlands 2 and i will murder ...
4       0  im getting into borderlands and i can murder y...

In [ ]:
df['data_type'] = ['not_set']*df.shape[0]

In [ ]:
df.head()

Rating                                            Reviews data_type
0       0  I am coming to the borders and I will kill you...   not_set
1       0  im getting on borderlands and i will kill you ...   not_set
2       0  im coming on borderlands and i will murder you...   not_set
3       0  im getting on borderlands 2 and i will murder ...   not_set
4       0  im getting into borderlands and i can murder y...   not_set

In [ ]:
df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'

In [ ]:
df

Rating                                            Reviews data_type
0           0  I am coming to the borders and I will kill you...     train
1           0  im getting on borderlands and i will kill you ...     train
2           0  im coming on borderlands and i will murder you...     train
3           0  im getting on borderlands 2 and i will murder ...     train
4           0  im getting into borderlands and i can murder y...     train
...       ...                                                ...       ...
74676       0  Just realized that the Windows partition of my...     train
74677       0  Just realized that my Mac window partition is ...     train
74678       0  Just realized the windows partition of my Mac ...       val
74679       0  Just realized between the windows partition of...     train
74680       0  Just like the windows partition of my Mac is l...       val

[73995 rows x 3 columns]

In [ ]:
df.groupby(['Rating', 'data_type']).count()

Reviews
Rating data_type         
0      train        17556
       val           3098
1      train        15391
       val           2717
2      train        19004
       val           3354
3      train        10944
       val           1931

3. Loading Tokenizer and Encoding our Data

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from transformers import BertTokenizer
from torch.utils.data import TensorDataset

In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    'bert-base-uncased',
    do_lower_case=True
)

In [ ]:
encoded_data_train = tokenizer.batch_encode_plus(
    
    df[df.data_type=='train'].Reviews.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

encoded_data_val = tokenizer.batch_encode_plus(
    df[df.data_type=='val'].Reviews.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(df[df.data_type=='train'].Rating.values)

input_ids_val = encoded_data_val['input_ids']
attention_masks_val = encoded_data_val['attention_mask']
labels_val = torch.tensor(df[df.data_type=='val'].Rating.values)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py:2339: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [ ]:
input_ids_train

tensor([[  101,  1045,  2572,  ...,     0,     0,     0],
        [  101, 10047,  2893,  ...,     0,     0,     0],
        [  101, 10047,  2746,  ...,     0,     0,     0],
        ...,
        [  101,  2074,  3651,  ...,     0,     0,     0],
        [  101,  2074,  3651,  ...,     0,     0,     0],
        [  101,  2074,  3651,  ...,     0,     0,     0]])

In [ ]:
dataset_train = TensorDataset(input_ids_train, 
                              attention_masks_train,
                              labels_train)

dataset_val = TensorDataset(input_ids_val, 
                            attention_masks_val,
                           labels_val)

In [ ]:
len(dataset_train)

62895

In [ ]:
dataset_val.tensors

(tensor([[  101,  2230,  2061,  ...,     0,     0,     0],
         [  101,  2600,  1011,  ...,     0,     0,     0],
         [  101,  2600,  1011,  ...,     0,     0,     0],
         ...,
         [  101, 10036,  2097,  ...,     0,     0,     0],
         [  101,  2074,  3651,  ...,     0,     0,     0],
         [  101,  2074,  2066,  ...,     0,     0,     0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([0, 1, 1,  ..., 2, 0, 0]))

4. Setting up BERT Pretrained Model

In [ ]:
from transformers import BertForSequenceClassification

In [ ]:
model = BertForSequenceClassification.from_pretrained(
                                      'bert-base-uncased', 
                                      num_labels = len(label_dict),#6
                                      output_attentions = False,
                                      output_hidden_states = False
                                     )

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

5. Creating Data Loaders

In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

In [ ]:
dataset_train

In [ ]:
batch_size = 4

dataloader_train = DataLoader(
    dataset_train,
    sampler=RandomSampler(dataset_train),
    batch_size=batch_size
)

dataloader_val = DataLoader(
    dataset_val,
    sampler=RandomSampler(dataset_val),
    batch_size=32
)

6. Setting Up Optimizer and Scheduler

In [ ]:
from transformers import AdamW, get_linear_schedule_with_warmup

In [ ]:
optimizer = AdamW(
    model.parameters(),
    lr = 1e-5,
    eps = 1e-8
)

/usr/local/lib/python3.9/dist-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
epochs = 1

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps = len(dataloader_train)*epochs
)

7. Defining our Performance Metrics

In [ ]:
import numpy as np
from sklearn.metrics import f1_score

In [ ]:
def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average = 'weighted')

In [ ]:
def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}
    
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    
    for label in np.unique(labels_flat):
        y_preds = preds_flat[labels_flat==label]
        y_true = labels_flat[labels_flat==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy:{len(y_preds[y_preds==label])}/{len(y_true)}\n')

8. Creating our Training Loop¶

In [ ]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
print(str(device).capitalize())

Cuda


In [ ]:
def evaluate(model, dataloader_val, device):
    loss_val_total = 0
    predictions, true_vals = [], []

    for batch in dataloader_val:
        batch = tuple(b.to(device) for b in batch)

        with torch.no_grad():
            inputs = {
                'input_ids': batch[0],
                'attention_mask': batch[1],
                'labels': batch[2]
            }

            outputs = model(**inputs)
            loss = outputs[0]
            logits = outputs[1]
            loss_val_total += loss.item()

            logits = logits.detach().cpu().numpy()
            label_ids = inputs['labels'].cpu().numpy()
            predictions.append(logits)
            true_vals.append(label_ids)

    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)

    return loss_val_total/len(dataloader_val), predictions, true_vals

In [ ]:
import os

os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

for epoch in tqdm(range(1, epochs+1)):
    model.train() #forward propagation
    loss_train_total = 0

    progress_bar = tqdm(dataloader_train, 
                        desc='Epoch {:1d}'.format(epoch), 
                        leave=False, 
                        disable=False)

    for batch in progress_bar:
        model.zero_grad()
        batch = tuple(b.to(device) for b in batch)
        inputs = {
            'input_ids': batch[0],
            'attention_mask': batch[1],
            'labels': batch[2]
        }

        outputs = model(**inputs)
        loss = outputs[0]
        loss_train_total +=loss.item()
        loss.backward() #backwardprop

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})     

    torch.save(model.state_dict(), f'BERT_ft_Epoch{epoch}.model')

    tqdm.write(f'\nEpoch {epoch}')

    loss_train_avg = loss_train_total/len(dataloader_train)
    tqdm.write(f'Training loss: {loss_train_avg}')

    val_loss, predictions, true_vals = evaluate(model, dataloader_val, device)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation loss: {val_loss}')
    tqdm.write(f'F1 Score (weighted): {val_f1}')

for batch in dataloader_val:
    batch = tuple(b.to(device) for b in batch)

    with torch.no_grad():
        inputs = {
            'input_ids': batch[0],
            'attention_mask': batch[1],
            'labels': batch[2]
        }

        outputs = model(**inputs)
        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)

predictions = np.concatenate(predictions, axis=0)
true_vals = np.concatenate(true_vals, axis=0)

return loss_val_total/len(dataloader_val), predictions, true_vals

  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/15724 [00:00<?, ?it/s]


Epoch 1
Training loss: 0.8423451525261054
Validation loss: 0.7144045777382699
F1 Score (weighted): 0.7406447574445102


NameError: ignored